### ISSUE TITLE
Studio: 기간 설정 / 세로 크기(width)가 작으면 위치가 깨집니다.

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2247]
## 버그 설명 ##
기간 설정 / 세로 크기(width)가 작으면 위치가 깨집니다.

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/83364933-d3858980-a3df-11ea-83e7-8beffa1a8394.png)

![image](https://user-images.githubusercontent.com/3411842/83364979-10518080-a3e0-11ea-94e6-453aac4a5569.png)

```css
report .tool.date:before {
    content: "";
    display: inline-block;
    height: 100%;
    width: 1px;
    vertical-align: middle;
}

report .tool.date-input .date-time {
    position: relative;
    z-index: 2;
    height: 26px;
    line-height: 26px;
    display: inline-block;
    vertical-align: middle;
    background: transparent url(/studio/images/common/icon_report_date-d3fa1d7….png) no-repeat 0 2px;
    padding-left: 26px;
    cursor: pointer;
}
```
