### ISSUE TITLE
Analyzer: 외부 링크 아이콘 깨짐

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#2307]
## 버그 설명 ##
Analyzer: 외부 링크 아이콘 깨짐

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/3411842/84717520-ff446a00-afb0-11ea-9f70-497b9e75c7d8.png)

## 상세
```html
<i class="mu-icon external-link"></i>
```
```css
.mu-icon.external-link:before {
    content: "\f08e";
}
```
