### ISSUE TITLE
[IRIS] 메뉴 구성 항목 글자 깨짐

### ISSUE THREAD

**Issue by cosmos-mc** [mobigen/IRIS-BigData-Platform#2405]
## 버그 설명 ##
{ 여기에 버그가 무엇인지에 대한 명확하고 간결한 설명 부탁드립니다.}
메뉴 구성 항목이 글자가 깨져서 나옵니다.

이 현상이 과거에도 있었는데 또 갑자기 발생하네요.

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }
![image](https://user-images.githubusercontent.com/61724098/86893866-3a176900-c13d-11ea-9580-94b0056dfb2f.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by rhcpn** [comment]
해당 현상이 다시 나타나서 살펴보니 아이콘이 깨지고 있었습니다.
![image](https://user-images.githubusercontent.com/11566844/87297986-53a52000-c544-11ea-9f10-31f3c41d18c6.png)

이때 iris.css 를 살펴보면 모든 css의 content 가 아래와 같이 깨져 있는것을 확인 하였습니다.
```css
.sub-menu-item--selected .sub-menu-item__arrow-icon:before {
    content: "î¤š"
}

.sub-menu-item__arrow-icon:before {
    font: normal normal normal 16px/1.25 iriscon;
    speak: none;
    text-transform: none;
    vertical-align: -.125em;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    content: "î¤œ"
}

.left-menu-item--selected .left-menu-item__arrow-icon:before {
    content: "î¤š"
}
...
```
정상일때는  content: ""
이렇게 나옵니다.
